software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: bionic-unstable
    production: bionic-stable

jobs:
  roger:
    builder: "golang"
    base: "quay.io/madebymany/build-bases:bionic"
    software_groups: *software
    packages:
      - type: debian
        name: roger
        depends:
          - libc6
        target: install
        repos:
          - mxm-public
        activates:
          - roger-upgrade
